export interface Country {
    value: string;
    labelEn: string;
    labelAr: string;
    nationalityEn: string;
    nationalityAr: string;
    dialCode: string;
}

export const WORLD_COUNTRIES: Country[] = [
    { value: 'Afghanistan', labelEn: 'Afghanistan', labelAr: 'أفغانستان', nationalityEn: 'Afghan', nationalityAr: 'أفغاني', dialCode: '+93' },
    { value: 'Albania', labelEn: 'Albania', labelAr: 'ألبانيا', nationalityEn: 'Albanian', nationalityAr: 'ألباني', dialCode: '+355' },
    { value: 'Algeria', labelEn: 'Algeria', labelAr: 'الجزائر', nationalityEn: 'Algerian', nationalityAr: 'جزائري', dialCode: '+213' },
    { value: 'Andorra', labelEn: 'Andorra', labelAr: 'أندورا', nationalityEn: 'Andorran', nationalityAr: 'أندوري', dialCode: '+376' },
    { value: 'Angola', labelEn: 'Angola', labelAr: 'أنغولا', nationalityEn: 'Angolan', nationalityAr: 'أنغولي', dialCode: '+244' },
    { value: 'Antigua and Barbuda', labelEn: 'Antigua and Barbuda', labelAr: 'أنتيغوا وبربودا', nationalityEn: 'Antiguan', nationalityAr: 'أنتيغوي', dialCode: '+1' },
    { value: 'Argentina', labelEn: 'Argentina', labelAr: 'الأرجنتين', nationalityEn: 'Argentine', nationalityAr: 'أرجنتيني', dialCode: '+54' },
    { value: 'Armenia', labelEn: 'Armenia', labelAr: 'أرمينيا', nationalityEn: 'Armenian', nationalityAr: 'أرمني', dialCode: '+374' },
    { value: 'Australia', labelEn: 'Australia', labelAr: 'أستراليا', nationalityEn: 'Australian', nationalityAr: 'أسترالي', dialCode: '+61' },
    { value: 'Austria', labelEn: 'Austria', labelAr: 'النمسا', nationalityEn: 'Austrian', nationalityAr: 'نمساوي', dialCode: '+43' },
    { value: 'Azerbaijan', labelEn: 'Azerbaijan', labelAr: 'أذربيجان', nationalityEn: 'Azerbaijani', nationalityAr: 'أذربيجاني', dialCode: '+994' },
    { value: 'Bahamas', labelEn: 'Bahamas', labelAr: 'جزر البهاما', nationalityEn: 'Bahamian', nationalityAr: 'بهامي', dialCode: '+1' },
    { value: 'Bahrain', labelEn: 'Bahrain', labelAr: 'البحرين', nationalityEn: 'Bahraini', nationalityAr: 'بحريني', dialCode: '+973' },
    { value: 'Bangladesh', labelEn: 'Bangladesh', labelAr: 'بنغلاديش', nationalityEn: 'Bangladeshi', nationalityAr: 'بنغلاديشي', dialCode: '+880' },
    { value: 'Barbados', labelEn: 'Barbados', labelAr: 'باربادوس', nationalityEn: 'Barbadian', nationalityAr: 'باربادوسي', dialCode: '+1' },
    { value: 'Belarus', labelEn: 'Belarus', labelAr: 'بيلاروسيا', nationalityEn: 'Belarusian', nationalityAr: 'بيلاروسي', dialCode: '+375' },
    { value: 'Belgium', labelEn: 'Belgium', labelAr: 'بلجيكا', nationalityEn: 'Belgian', nationalityAr: 'بلجيكي', dialCode: '+32' },
    { value: 'Belize', labelEn: 'Belize', labelAr: 'بليز', nationalityEn: 'Belizean', nationalityAr: 'بليزي', dialCode: '+501' },
    { value: 'Benin', labelEn: 'Benin', labelAr: 'بنين', nationalityEn: 'Beninese', nationalityAr: 'بنيني', dialCode: '+229' },
    { value: 'Bhutan', labelEn: 'Bhutan', labelAr: 'بوتان', nationalityEn: 'Bhutanese', nationalityAr: 'بوتاني', dialCode: '+975' },
    { value: 'Bolivia', labelEn: 'Bolivia', labelAr: 'بوليفيا', nationalityEn: 'Bolivian', nationalityAr: 'بوليفي', dialCode: '+591' },
    { value: 'Bosnia and Herzegovina', labelEn: 'Bosnia and Herzegovina', labelAr: 'البوسنة والهرسك', nationalityEn: 'Bosnian', nationalityAr: 'بوسني', dialCode: '+387' },
    { value: 'Botswana', labelEn: 'Botswana', labelAr: 'بوتسوانا', nationalityEn: 'Botswanan', nationalityAr: 'بوتسواني', dialCode: '+267' },
    { value: 'Brazil', labelEn: 'Brazil', labelAr: 'البرازيل', nationalityEn: 'Brazilian', nationalityAr: 'برازيلي', dialCode: '+55' },
    { value: 'Brunei', labelEn: 'Brunei', labelAr: 'بروناي', nationalityEn: 'Bruneian', nationalityAr: 'برونايي', dialCode: '+673' },
    { value: 'Bulgaria', labelEn: 'Bulgaria', labelAr: 'بلغاريا', nationalityEn: 'Bulgarian', nationalityAr: 'بلغاري', dialCode: '+359' },
    { value: 'Burkina Faso', labelEn: 'Burkina Faso', labelAr: 'بوركينا فاسو', nationalityEn: 'Burkinabe', nationalityAr: 'بوركيني', dialCode: '+226' },
    { value: 'Burundi', labelEn: 'Burundi', labelAr: 'بوروندي', nationalityEn: 'Burundian', nationalityAr: 'بوروندي', dialCode: '+257' },
    { value: 'Cabo Verde', labelEn: 'Cabo Verde', labelAr: 'الرأس الأخضر', nationalityEn: 'Cape Verdean', nationalityAr: 'رأس أخضري', dialCode: '+238' },
    { value: 'Cambodia', labelEn: 'Cambodia', labelAr: 'كمبوديا', nationalityEn: 'Cambodian', nationalityAr: 'كمبودي', dialCode: '+855' },
    { value: 'Cameroon', labelEn: 'Cameroon', labelAr: 'الكاميرون', nationalityEn: 'Cameroonian', nationalityAr: 'كاميروني', dialCode: '+237' },
    { value: 'Canada', labelEn: 'Canada', labelAr: 'كندا', nationalityEn: 'Canadian', nationalityAr: 'كندي', dialCode: '+1' },
    { value: 'Central African Republic', labelEn: 'Central African Republic', labelAr: 'جمهورية أفريقيا الوسطى', nationalityEn: 'Central African', nationalityAr: 'وسط أفريقي', dialCode: '+236' },
    { value: 'Chad', labelEn: 'Chad', labelAr: 'تشاد', nationalityEn: 'Chadian', nationalityAr: 'تشادي', dialCode: '+235' },
    { value: 'Chile', labelEn: 'Chile', labelAr: 'تشيلي', nationalityEn: 'Chilean', nationalityAr: 'تشيلي', dialCode: '+56' },
    { value: 'China', labelEn: 'China', labelAr: 'الصين', nationalityEn: 'Chinese', nationalityAr: 'صيني', dialCode: '+86' },
    { value: 'Colombia', labelEn: 'Colombia', labelAr: 'كولومبيا', nationalityEn: 'Colombian', nationalityAr: 'كولومبي', dialCode: '+57' },
    { value: 'Comoros', labelEn: 'Comoros', labelAr: 'جزر القمر', nationalityEn: 'Comorian', nationalityAr: 'قمري', dialCode: '+269' },
    { value: 'Congo', labelEn: 'Congo', labelAr: 'الكونغو', nationalityEn: 'Congolese', nationalityAr: 'كونغولي', dialCode: '+242' },
    { value: 'Costa Rica', labelEn: 'Costa Rica', labelAr: 'كوستاريكا', nationalityEn: 'Costa Rican', nationalityAr: 'كوستاريكي', dialCode: '+506' },
    { value: 'Croatia', labelEn: 'Croatia', labelAr: 'كرواتيا', nationalityEn: 'Croatian', nationalityAr: 'كرواتي', dialCode: '+385' },
    { value: 'Cuba', labelEn: 'Cuba', labelAr: 'كوبا', nationalityEn: 'Cuban', nationalityAr: 'كوبي', dialCode: '+53' },
    { value: 'Cyprus', labelEn: 'Cyprus', labelAr: 'قبرص', nationalityEn: 'Cypriot', nationalityAr: 'قبرصي', dialCode: '+357' },
    { value: 'Czechia', labelEn: 'Czechia', labelAr: 'التشيك', nationalityEn: 'Czech', nationalityAr: 'تشيكي', dialCode: '+420' },
    { value: 'Denmark', labelEn: 'Denmark', labelAr: 'الدنمارك', nationalityEn: 'Danish', nationalityAr: 'دنماركي', dialCode: '+45' },
    { value: 'Djibouti', labelEn: 'Djibouti', labelAr: 'جيبوتي', nationalityEn: 'Djiboutian', nationalityAr: 'جيبوتي', dialCode: '+253' },
    { value: 'Dominica', labelEn: 'Dominica', labelAr: 'دومينيكا', nationalityEn: 'Dominican', nationalityAr: 'دومينيكي', dialCode: '+1' },
    { value: 'Dominican Republic', labelEn: 'Dominican Republic', labelAr: 'جمهورية الدومينيكان', nationalityEn: 'Dominican', nationalityAr: 'دومينيكاني', dialCode: '+1' },
    { value: 'Ecuador', labelEn: 'Ecuador', labelAr: 'الإكوادور', nationalityEn: 'Ecuadorian', nationalityAr: 'إكوادوري', dialCode: '+593' },
    { value: 'Egypt', labelEn: 'Egypt', labelAr: 'مصر', nationalityEn: 'Egyptian', nationalityAr: 'مصري', dialCode: '+20' },
    { value: 'El Salvador', labelEn: 'El Salvador', labelAr: 'السلفادور', nationalityEn: 'Salvadoran', nationalityAr: 'سلفادوري', dialCode: '+503' },
    { value: 'Equatorial Guinea', labelEn: 'Equatorial Guinea', labelAr: 'غينيا الاستوائية', nationalityEn: 'Equatorial Guinean', nationalityAr: 'غيني استوائي', dialCode: '+240' },
    { value: 'Eritrea', labelEn: 'Eritrea', labelAr: 'إريتريا', nationalityEn: 'Eritrean', nationalityAr: 'إريتري', dialCode: '+291' },
    { value: 'Estonia', labelEn: 'Estonia', labelAr: 'إستونيا', nationalityEn: 'Estonian', nationalityAr: 'إستوني', dialCode: '+372' },
    { value: 'Eswatini', labelEn: 'Eswatini', labelAr: 'إسواتيني', nationalityEn: 'Swazi', nationalityAr: 'إسواتيني', dialCode: '+268' },
    { value: 'Ethiopia', labelEn: 'Ethiopia', labelAr: 'إثيوبيا', nationalityEn: 'Ethiopian', nationalityAr: 'إثيوبي', dialCode: '+251' },
    { value: 'Fiji', labelEn: 'Fiji', labelAr: 'فيجي', nationalityEn: 'Fijian', nationalityAr: 'فيجي', dialCode: '+679' },
    { value: 'Finland', labelEn: 'Finland', labelAr: 'فنلندا', nationalityEn: 'Finnish', nationalityAr: 'فنلندي', dialCode: '+358' },
    { value: 'France', labelEn: 'France', labelAr: 'فرنسا', nationalityEn: 'French', nationalityAr: 'فرنسي', dialCode: '+33' },
    { value: 'Gabon', labelEn: 'Gabon', labelAr: 'الغابون', nationalityEn: 'Gabonese', nationalityAr: 'غابوني', dialCode: '+241' },
    { value: 'Gambia', labelEn: 'Gambia', labelAr: 'غامبيا', nationalityEn: 'Gambian', nationalityAr: 'غامبي', dialCode: '+220' },
    { value: 'Georgia', labelEn: 'Georgia', labelAr: 'جورجيا', nationalityEn: 'Georgian', nationalityAr: 'جورجي', dialCode: '+995' },
    { value: 'Germany', labelEn: 'Germany', labelAr: 'ألمانيا', nationalityEn: 'German', nationalityAr: 'ألماني', dialCode: '+49' },
    { value: 'Ghana', labelEn: 'Ghana', labelAr: 'غانا', nationalityEn: 'Ghanaian', nationalityAr: 'غاني', dialCode: '+233' },
    { value: 'Greece', labelEn: 'Greece', labelAr: 'اليونان', nationalityEn: 'Greek', nationalityAr: 'يوناني', dialCode: '+30' },
    { value: 'Grenada', labelEn: 'Grenada', labelAr: 'غرينادا', nationalityEn: 'Grenadian', nationalityAr: 'غرينادي', dialCode: '+1' },
    { value: 'Guatemala', labelEn: 'Guatemala', labelAr: 'غواتيمالا', nationalityEn: 'Guatemalan', nationalityAr: 'غواتيمالي', dialCode: '+502' },
    { value: 'Guinea', labelEn: 'Guinea', labelAr: 'غينيا', nationalityEn: 'Guinean', nationalityAr: 'غيني', dialCode: '+224' },
    { value: 'Guinea-Bissau', labelEn: 'Guinea-Bissau', labelAr: 'غينيا بيساو', nationalityEn: 'Bissau-Guinean', nationalityAr: 'غينيا بيساوي', dialCode: '+245' },
    { value: 'Guyana', labelEn: 'Guyana', labelAr: 'غويانا', nationalityEn: 'Guyanese', nationalityAr: 'غوياني', dialCode: '+592' },
    { value: 'Haiti', labelEn: 'Haiti', labelAr: 'هايتي', nationalityEn: 'Haitian', nationalityAr: 'هايتي', dialCode: '+509' },
    { value: 'Honduras', labelEn: 'Honduras', labelAr: 'هندوراس', nationalityEn: 'Honduran', nationalityAr: 'هندوراسي', dialCode: '+504' },
    { value: 'Hungary', labelEn: 'Hungary', labelAr: 'المجر', nationalityEn: 'Hungarian', nationalityAr: 'هنغاري', dialCode: '+36' },
    { value: 'Iceland', labelEn: 'Iceland', labelAr: 'آيسلندا', nationalityEn: 'Icelandic', nationalityAr: 'آيسلندي', dialCode: '+354' },
    { value: 'India', labelEn: 'India', labelAr: 'الهند', nationalityEn: 'Indian', nationalityAr: 'هندي', dialCode: '+91' },
    { value: 'Indonesia', labelEn: 'Indonesia', labelAr: 'إندونيسيا', nationalityEn: 'Indonesian', nationalityAr: 'إندونيسي', dialCode: '+62' },
    { value: 'Iran', labelEn: 'Iran', labelAr: 'إيران', nationalityEn: 'Iranian', nationalityAr: 'إيراني', dialCode: '+98' },
    { value: 'Iraq', labelEn: 'Iraq', labelAr: 'العراق', nationalityEn: 'Iraqi', nationalityAr: 'عراقي', dialCode: '+964' },
    { value: 'Ireland', labelEn: 'Ireland', labelAr: 'أيرلندا', nationalityEn: 'Irish', nationalityAr: 'أيرلندي', dialCode: '+353' },
    { value: 'Palestine', labelEn: 'Palestine', labelAr: 'فلسطين', nationalityEn: 'Palestinian', nationalityAr: 'فلسطيني', dialCode: '+970' },
    { value: 'Italy', labelEn: 'Italy', labelAr: 'إيطاليا', nationalityEn: 'Italian', nationalityAr: 'إيطالي', dialCode: '+39' },
    { value: 'Ivory Coast', labelEn: 'Ivory Coast', labelAr: 'ساحل العاج', nationalityEn: 'Ivorian', nationalityAr: 'إيفواري', dialCode: '+225' },
    { value: 'Jamaica', labelEn: 'Jamaica', labelAr: 'جامايكا', nationalityEn: 'Jamaican', nationalityAr: 'جامايكي', dialCode: '+1' },
    { value: 'Japan', labelEn: 'Japan', labelAr: 'اليابان', nationalityEn: 'Japanese', nationalityAr: 'ياباني', dialCode: '+81' },
    { value: 'Jordan', labelEn: 'Jordan', labelAr: 'الأردن', nationalityEn: 'Jordanian', nationalityAr: 'أردني', dialCode: '+962' },
    { value: 'Kazakhstan', labelEn: 'Kazakhstan', labelAr: 'كازاخستان', nationalityEn: 'Kazakh', nationalityAr: 'كازاخستاني', dialCode: '+7' },
    { value: 'Kenya', labelEn: 'Kenya', labelAr: 'كينيا', nationalityEn: 'Kenyan', nationalityAr: 'كيني', dialCode: '+254' },
    { value: 'Kiribati', labelEn: 'Kiribati', labelAr: 'كيريباتي', nationalityEn: 'I-Kiribati', nationalityAr: 'كيريباتي', dialCode: '+686' },
    { value: 'Kosovo', labelEn: 'Kosovo', labelAr: 'كوسوفو', nationalityEn: 'Kosovar', nationalityAr: 'كوسوفي', dialCode: '+383' },
    { value: 'Kuwait', labelEn: 'Kuwait', labelAr: 'الكويت', nationalityEn: 'Kuwaiti', nationalityAr: 'كويتي', dialCode: '+965' },
    { value: 'Kyrgyzstan', labelEn: 'Kyrgyzstan', labelAr: 'قيرغيزستان', nationalityEn: 'Kyrgyz', nationalityAr: 'قيرغيزستاني', dialCode: '+996' },
    { value: 'Laos', labelEn: 'Laos', labelAr: 'لاوس', nationalityEn: 'Lao', nationalityAr: 'لاوسي', dialCode: '+856' },
    { value: 'Latvia', labelEn: 'Latvia', labelAr: 'لاتفيا', nationalityEn: 'Latvian', nationalityAr: 'لاتفي', dialCode: '+371' },
    { value: 'Lebanon', labelEn: 'Lebanon', labelAr: 'لبنان', nationalityEn: 'Lebanese', nationalityAr: 'لبناني', dialCode: '+961' },
    { value: 'Lesotho', labelEn: 'Lesotho', labelAr: 'ليسوتو', nationalityEn: 'Mosotho', nationalityAr: 'ليسوتي', dialCode: '+266' },
    { value: 'Liberia', labelEn: 'Liberia', labelAr: 'ليبيريا', nationalityEn: 'Liberian', nationalityAr: 'ليبيري', dialCode: '+231' },
    { value: 'Libya', labelEn: 'Libya', labelAr: 'ليبيا', nationalityEn: 'Libyan', nationalityAr: 'ليبي', dialCode: '+218' },
    { value: 'Liechtenstein', labelEn: 'Liechtenstein', labelAr: 'ليختنشتاين', nationalityEn: 'Liechtensteiner', nationalityAr: 'ليختنشتايني', dialCode: '+423' },
    { value: 'Lithuania', labelEn: 'Lithuania', labelAr: 'ليتوانيا', nationalityEn: 'Lithuanian', nationalityAr: 'ليتواني', dialCode: '+370' },
    { value: 'Luxembourg', labelEn: 'Luxembourg', labelAr: 'لوكسمبورغ', nationalityEn: 'Luxembourgish', nationalityAr: 'لوكسمبورغي', dialCode: '+352' },
    { value: 'Madagascar', labelEn: 'Madagascar', labelAr: 'مدغشقر', nationalityEn: 'Malagasy', nationalityAr: 'مدغشقري', dialCode: '+261' },
    { value: 'Malawi', labelEn: 'Malawi', labelAr: 'مالاوي', nationalityEn: 'Malawian', nationalityAr: 'مالاوي', dialCode: '+265' },
    { value: 'Malaysia', labelEn: 'Malaysia', labelAr: 'ماليزيا', nationalityEn: 'Malaysian', nationalityAr: 'ماليزي', dialCode: '+60' },
    { value: 'Maldives', labelEn: 'Maldives', labelAr: 'جزر المالديف', nationalityEn: 'Maldivian', nationalityAr: 'مالديفي', dialCode: '+960' },
    { value: 'Mali', labelEn: 'Mali', labelAr: 'مالي', nationalityEn: 'Malian', nationalityAr: 'مالي', dialCode: '+223' },
    { value: 'Malta', labelEn: 'Malta', labelAr: 'مالطا', nationalityEn: 'Maltese', nationalityAr: 'مالطي', dialCode: '+356' },
    { value: 'Marshall Islands', labelEn: 'Marshall Islands', labelAr: 'جزر مارشال', nationalityEn: 'Marshallese', nationalityAr: 'مارشالي', dialCode: '+692' },
    { value: 'Mauritania', labelEn: 'Mauritania', labelAr: 'موريتانيا', nationalityEn: 'Mauritanian', nationalityAr: 'موريتاني', dialCode: '+222' },
    { value: 'Mauritius', labelEn: 'Mauritius', labelAr: 'موريشيوس', nationalityEn: 'Mauritian', nationalityAr: 'موريشيوسي', dialCode: '+230' },
    { value: 'Mexico', labelEn: 'Mexico', labelAr: 'المكسيك', nationalityEn: 'Mexican', nationalityAr: 'مكسيكي', dialCode: '+52' },
    { value: 'Micronesia', labelEn: 'Micronesia', labelAr: 'ميكرونيزيا', nationalityEn: 'Micronesian', nationalityAr: 'ميكرونيزي', dialCode: '+691' },
    { value: 'Moldova', labelEn: 'Moldova', labelAr: 'مولدوفا', nationalityEn: 'Moldovan', nationalityAr: 'مولدوفي', dialCode: '+373' },
    { value: 'Monaco', labelEn: 'Monaco', labelAr: 'موناكو', nationalityEn: 'Monegasque', nationalityAr: 'موناكوي', dialCode: '+377' },
    { value: 'Mongolia', labelEn: 'Mongolia', labelAr: 'منغوليا', nationalityEn: 'Mongolian', nationalityAr: 'منغولي', dialCode: '+976' },
    { value: 'Montenegro', labelEn: 'Montenegro', labelAr: 'مونتينيغرو (الجبل الأسود)', nationalityEn: 'Montenegrin', nationalityAr: 'مونتينيغري', dialCode: '+382' },
    { value: 'Morocco', labelEn: 'Morocco', labelAr: 'المغرب', nationalityEn: 'Moroccan', nationalityAr: 'مغربي', dialCode: '+212' },
    { value: 'Mozambique', labelEn: 'Mozambique', labelAr: 'موزمبيق', nationalityEn: 'Mozambican', nationalityAr: 'موزمبيقي', dialCode: '+258' },
    { value: 'Myanmar', labelEn: 'Myanmar', labelAr: 'ميانمار', nationalityEn: 'Burmese', nationalityAr: 'ميانماري', dialCode: '+95' },
    { value: 'Namibia', labelEn: 'Namibia', labelAr: 'ناميبيا', nationalityEn: 'Namibian', nationalityAr: 'ناميبي', dialCode: '+264' },
    { value: 'Nauru', labelEn: 'Nauru', labelAr: 'ناورو', nationalityEn: 'Nauruan', nationalityAr: 'ناوروي', dialCode: '+674' },
    { value: 'Nepal', labelEn: 'Nepal', labelAr: 'نيبال', nationalityEn: 'Nepali', nationalityAr: 'نيبالي', dialCode: '+977' },
    { value: 'Netherlands', labelEn: 'Netherlands', labelAr: 'هولندا', nationalityEn: 'Dutch', nationalityAr: 'هولندي', dialCode: '+31' },
    { value: 'New Zealand', labelEn: 'New Zealand', labelAr: 'نيوزيلندا', nationalityEn: 'New Zealander', nationalityAr: 'نيوزيلندي', dialCode: '+64' },
    { value: 'Nicaragua', labelEn: 'Nicaragua', labelAr: 'نيكاراغوا', nationalityEn: 'Nicaraguan', nationalityAr: 'نيكاراغوي', dialCode: '+505' },
    { value: 'Niger', labelEn: 'Niger', labelAr: 'النيجر', nationalityEn: 'Nigerien', nationalityAr: 'نيجري', dialCode: '+227' },
    { value: 'Nigeria', labelEn: 'Nigeria', labelAr: 'نيجيريا', nationalityEn: 'Nigerian', nationalityAr: 'نيجيري', dialCode: '+234' },
    { value: 'North Korea', labelEn: 'North Korea', labelAr: 'كوريا الشمالية', nationalityEn: 'North Korean', nationalityAr: 'كوري شمالي', dialCode: '+850' },
    { value: 'North Macedonia', labelEn: 'North Macedonia', labelAr: 'مقدونيا الشمالية', nationalityEn: 'North Macedonian', nationalityAr: 'مقدوني شمالي', dialCode: '+389' },
    { value: 'Norway', labelEn: 'Norway', labelAr: 'النرويج', nationalityEn: 'Norwegian', nationalityAr: 'نرويجي', dialCode: '+47' },
    { value: 'Oman', labelEn: 'Oman', labelAr: 'عمان', nationalityEn: 'Omani', nationalityAr: 'عماني', dialCode: '+968' },
    { value: 'Pakistan', labelEn: 'Pakistan', labelAr: 'باكستان', nationalityEn: 'Pakistani', nationalityAr: 'باكستاني', dialCode: '+92' },
    { value: 'Palau', labelEn: 'Palau', labelAr: 'بالاو', nationalityEn: 'Palauan', nationalityAr: 'بالاوي', dialCode: '+680' },
    { value: 'Panama', labelEn: 'Panama', labelAr: 'بنما', nationalityEn: 'Panamanian', nationalityAr: 'بنمي', dialCode: '+507' },
    { value: 'Papua New Guinea', labelEn: 'Papua New Guinea', labelAr: 'بابوا غينيا الجديدة', nationalityEn: 'Papua New Guinean', nationalityAr: 'بابوا غيني', dialCode: '+675' },
    { value: 'Paraguay', labelEn: 'Paraguay', labelAr: 'باراغواي', nationalityEn: 'Paraguayan', nationalityAr: 'باراغواياني', dialCode: '+595' },
    { value: 'Peru', labelEn: 'Peru', labelAr: 'بيرو', nationalityEn: 'Peruvian', nationalityAr: 'بيروفي', dialCode: '+51' },
    { value: 'Philippines', labelEn: 'Philippines', labelAr: 'الفلبين', nationalityEn: 'Filipino', nationalityAr: 'فلبيني', dialCode: '+63' },
    { value: 'Poland', labelEn: 'Poland', labelAr: 'بولندا', nationalityEn: 'Polish', nationalityAr: 'بولندي', dialCode: '+48' },
    { value: 'Portugal', labelEn: 'Portugal', labelAr: 'البرتغال', nationalityEn: 'Portuguese', nationalityAr: 'برتغالي', dialCode: '+351' },
    { value: 'Qatar', labelEn: 'Qatar', labelAr: 'قطر', nationalityEn: 'Qatari', nationalityAr: 'قطري', dialCode: '+974' },
    { value: 'Romania', labelEn: 'Romania', labelAr: 'رومانيا', nationalityEn: 'Romanian', nationalityAr: 'روماني', dialCode: '+40' },
    { value: 'Russia', labelEn: 'Russia', labelAr: 'روسيا', nationalityEn: 'Russian', nationalityAr: 'روسي', dialCode: '+7' },
    { value: 'Rwanda', labelEn: 'Rwanda', labelAr: 'رواندا', nationalityEn: 'Rwandan', nationalityAr: 'رواندي', dialCode: '+250' },
    { value: 'Saint Kitts and Nevis', labelEn: 'Saint Kitts and Nevis', labelAr: 'سانت كيتس ونيفيس', nationalityEn: 'Kittitian or Nevisian', nationalityAr: 'سانت كيتسي', dialCode: '+1' },
    { value: 'Saint Lucia', labelEn: 'Saint Lucia', labelAr: 'سانت لوسيا', nationalityEn: 'Saint Lucian', nationalityAr: 'سانت لوسي', dialCode: '+1' },
    { value: 'Saint Vincent and the Grenadines', labelEn: 'Saint Vincent and the Grenadines', labelAr: 'سانت فينسنت والغرينادين', nationalityEn: 'Vincentian', nationalityAr: 'فينسنتي', dialCode: '+1' },
    { value: 'Samoa', labelEn: 'Samoa', labelAr: 'ساموا', nationalityEn: 'Samoan', nationalityAr: 'ساموي', dialCode: '+685' },
    { value: 'San Marino', labelEn: 'San Marino', labelAr: 'سان مارينو', nationalityEn: 'Sammarinese', nationalityAr: 'سان مارينوي', dialCode: '+378' },
    { value: 'Sao Tome and Principe', labelEn: 'Sao Tome and Principe', labelAr: 'ساو تومي وبرينسيب', nationalityEn: 'Sao Tomean', nationalityAr: 'ساو تومي', dialCode: '+239' },
    { value: 'Saudi Arabia', labelEn: 'Saudi Arabia', labelAr: 'المملكة العربية السعودية', nationalityEn: 'Saudi', nationalityAr: 'سعودي', dialCode: '+966' },
    { value: 'Senegal', labelEn: 'Senegal', labelAr: 'السنغال', nationalityEn: 'Senegalese', nationalityAr: 'سنغالي', dialCode: '+221' },
    { value: 'Serbia', labelEn: 'Serbia', labelAr: 'صربيا', nationalityEn: 'Serbian', nationalityAr: 'صربي', dialCode: '+381' },
    { value: 'Seychelles', labelEn: 'Seychelles', labelAr: 'سيشل', nationalityEn: 'Seychellois', nationalityAr: 'سيشلي', dialCode: '+248' },
    { value: 'Sierra Leone', labelEn: 'Sierra Leone', labelAr: 'سيراليون', nationalityEn: 'Sierra Leonean', nationalityAr: 'سيراليوني', dialCode: '+232' },
    { value: 'Singapore', labelEn: 'Singapore', labelAr: 'سنغافورة', nationalityEn: 'Singaporean', nationalityAr: 'سنغافوري', dialCode: '+65' },
    { value: 'Slovakia', labelEn: 'Slovakia', labelAr: 'سلوفاكيا', nationalityEn: 'Slovak', nationalityAr: 'سلوفاكي', dialCode: '+421' },
    { value: 'Slovenia', labelEn: 'Slovenia', labelAr: 'سلوفينيا', nationalityEn: 'Slovenian', nationalityAr: 'سلوفيني', dialCode: '+386' },
    { value: 'Solomon Islands', labelEn: 'Solomon Islands', labelAr: 'جزر سليمان', nationalityEn: 'Solomon Islander', nationalityAr: 'جزر سليماني', dialCode: '+677' },
    { value: 'Somalia', labelEn: 'Somalia', labelAr: 'الصومال', nationalityEn: 'Somali', nationalityAr: 'صومالي', dialCode: '+252' },
    { value: 'South Africa', labelEn: 'South Africa', labelAr: 'جنوب أفريقيا', nationalityEn: 'South African', nationalityAr: 'جنوب أفريقي', dialCode: '+27' },
    { value: 'South Korea', labelEn: 'South Korea', labelAr: 'كوريا الجنوبية', nationalityEn: 'South Korean', nationalityAr: 'كوري جنوبي', dialCode: '+82' },
    { value: 'South Sudan', labelEn: 'South Sudan', labelAr: 'جنوب السودان', nationalityEn: 'South Sudanese', nationalityAr: 'جنوب سوداني', dialCode: '+211' },
    { value: 'Spain', labelEn: 'Spain', labelAr: 'إسبانيا', nationalityEn: 'Spanish', nationalityAr: 'إسباني', dialCode: '+34' },
    { value: 'Sri Lanka', labelEn: 'Sri Lanka', labelAr: 'سريلانكا', nationalityEn: 'Sri Lankan', nationalityAr: 'سريلانكي', dialCode: '+94' },
    { value: 'Sudan', labelEn: 'Sudan', labelAr: 'السودان', nationalityEn: 'Sudanese', nationalityAr: 'سوداني', dialCode: '+249' },
    { value: 'Suriname', labelEn: 'Suriname', labelAr: 'سورينام', nationalityEn: 'Surinamese', nationalityAr: 'سورينامي', dialCode: '+597' },
    { value: 'Sweden', labelEn: 'Sweden', labelAr: 'السويد', nationalityEn: 'Swedish', nationalityAr: 'سويدي', dialCode: '+46' },
    { value: 'Switzerland', labelEn: 'Switzerland', labelAr: 'سويسرا', nationalityEn: 'Swiss', nationalityAr: 'سويسري', dialCode: '+41' },
    { value: 'Syria', labelEn: 'Syria', labelAr: 'سوريا', nationalityEn: 'Syrian', nationalityAr: 'سوري', dialCode: '+963' },
    { value: 'Taiwan', labelEn: 'Taiwan', labelAr: 'تايوان', nationalityEn: 'Taiwanese', nationalityAr: 'تايواني', dialCode: '+886' },
    { value: 'Tajikistan', labelEn: 'Tajikistan', labelAr: 'طاجيكستان', nationalityEn: 'Tajik', nationalityAr: 'طاجيكي', dialCode: '+992' },
    { value: 'Tanzania', labelEn: 'Tanzania', labelAr: 'تنزانيا', nationalityEn: 'Tanzanian', nationalityAr: 'تنزاني', dialCode: '+255' },
    { value: 'Thailand', labelEn: 'Thailand', labelAr: 'تايلاند', nationalityEn: 'Thai', nationalityAr: 'تايلاندي', dialCode: '+66' },
    { value: 'Timor-Leste', labelEn: 'Timor-Leste', labelAr: 'تيمور الشرقية', nationalityEn: 'Timorese', nationalityAr: 'تيموري', dialCode: '+670' },
    { value: 'Togo', labelEn: 'Togo', labelAr: 'توغو', nationalityEn: 'Togolese', nationalityAr: 'توغولي', dialCode: '+228' },
    { value: 'Tonga', labelEn: 'Tonga', labelAr: 'تونغا', nationalityEn: 'Tongan', nationalityAr: 'تونغي', dialCode: '+676' },
    { value: 'Trinidad and Tobago', labelEn: 'Trinidad and Tobago', labelAr: 'ترينيداد وتوباغو', nationalityEn: 'Trinidadian', nationalityAr: 'ترينيدادي', dialCode: '+1' },
    { value: 'Tunisia', labelEn: 'Tunisia', labelAr: 'تونس', nationalityEn: 'Tunisian', nationalityAr: 'تونسي', dialCode: '+216' },
    { value: 'Turkey', labelEn: 'Turkey', labelAr: 'تركيا', nationalityEn: 'Turkish', nationalityAr: 'تركي', dialCode: '+90' },
    { value: 'Turkmenistan', labelEn: 'Turkmenistan', labelAr: 'تركمانستان', nationalityEn: 'Turkmen', nationalityAr: 'تركماني', dialCode: '+993' },
    { value: 'Tuvalu', labelEn: 'Tuvalu', labelAr: 'توفالو', nationalityEn: 'Tuvaluan', nationalityAr: 'توفالوي', dialCode: '+688' },
    { value: 'Uganda', labelEn: 'Uganda', labelAr: 'أوغندا', nationalityEn: 'Ugandan', nationalityAr: 'أوغندي', dialCode: '+256' },
    { value: 'Ukraine', labelEn: 'Ukraine', labelAr: 'أوكرانيا', nationalityEn: 'Ukrainian', nationalityAr: 'أوكراني', dialCode: '+380' },
    { value: 'United Arab Emirates', labelEn: 'United Arab Emirates', labelAr: 'الإمارات العربية المتحدة', nationalityEn: 'Emirati', nationalityAr: 'إماراتي', dialCode: '+971' },
    { value: 'United Kingdom', labelEn: 'United Kingdom', labelAr: 'المملكة المتحدة', nationalityEn: 'British', nationalityAr: 'بريطاني', dialCode: '+44' },
    { value: 'United States of America', labelEn: 'United States', labelAr: 'الولايات المتحدة', nationalityEn: 'American', nationalityAr: 'أمريكي', dialCode: '+1' },
    { value: 'Uruguay', labelEn: 'Uruguay', labelAr: 'الأوروغواي', nationalityEn: 'Uruguayan', nationalityAr: 'أوروغواياني', dialCode: '+598' },
    { value: 'Uzbekistan', labelEn: 'Uzbekistan', labelAr: 'أوزبكستان', nationalityEn: 'Uzbek', nationalityAr: 'أوزبكي', dialCode: '+998' },
    { value: 'Vanuatu', labelEn: 'Vanuatu', labelAr: 'فانواتو', nationalityEn: 'Vanuatuan', nationalityAr: 'فانواتوي', dialCode: '+678' },
    { value: 'Vatican City', labelEn: 'Vatican City', labelAr: 'الفاتيكان', nationalityEn: 'Vatican', nationalityAr: 'فاتيكاني', dialCode: '+379' },
    { value: 'Venezuela', labelEn: 'Venezuela', labelAr: 'فنزويلا', nationalityEn: 'Venezuelan', nationalityAr: 'فنزويلي', dialCode: '+58' },
    { value: 'Vietnam', labelEn: 'Vietnam', labelAr: 'فيتنام', nationalityEn: 'Vietnamese', nationalityAr: 'فيتنامي', dialCode: '+84' },
    { value: 'Yemen', labelEn: 'Yemen', labelAr: 'اليمن', nationalityEn: 'Yemeni', nationalityAr: 'يمني', dialCode: '+967' },
    { value: 'Zambia', labelEn: 'Zambia', labelAr: 'زامبيا', nationalityEn: 'Zambian', nationalityAr: 'زامبي', dialCode: '+260' },
    { value: 'Zimbabwe', labelEn: 'Zimbabwe', labelAr: 'زيمبابوي', nationalityEn: 'Zimbabwean', nationalityAr: 'زيمبابوي', dialCode: '+263' }
];
